Contribution On Some Essential Tools for Frontend Web Development
jobream/List-of-Learning-Resources pull request #106
Opened 2022-01-18 17:48 UTC by Ilsa-Naeem

2022-01-19 20:31 UTC, CodingSpecies requested changes
@Ilsa-Naeem please revert the changes you made in the .all-contributorssrc file, we will do that ourselves after your pr is merged. Thank you.

2022-01-20 01:00 UTC, Ilsa-Naeem commented
@CodingSpecies i have removed the changes made in .all-contributorssrc file

2022-01-22 14:58 UTC, CodingSpecies requested changes

2022-01-22 14:58 UTC, CodingSpecies commented on .all-contributorsrc
> -    },
Please add line 159 back, but remove the comma please @Ilsa-Naeem

2022-01-23 23:41 UTC, TheSlimCoder approved these changes
@CodingSpecies I did it by myself @Ilsa-Naeem merging PR.

2022-01-23 23:42 UTC, merged

2022-01-23 23:42 UTC, TheSlimCoder commented
@all-contributors add @Ilsa-Naeem for content.