Changes in Readme.md
jobream/List-of-Learning-Resources pull request #113
Opened 2022-02-17 03:48 UTC by shaggyyy2002

Added new resources for Computer Networking and Git-Github. (0-100) complete for free.

2022-02-18 20:51 UTC, CodingSpecies requested changes

2022-02-18 20:51 UTC, CodingSpecies commented on README.md
> -> If you think there is a resource which you think others would benefit on, fork, and your changes, and make a pull request!
Please can you add line 67 and 68 back please @shaggyyy2002 .

2022-02-18 20:51 UTC, CodingSpecies commented on README.md
>  ### 2. Video Courses - Here are 2 from our range :
Please change `2. Video Courses - Here are 2 from our range :` to `2. Video Courses - Here are 3 from our range :` @shaggyyy2002 . Thank you.

2022-02-19 21:45 UTC, CodingSpecies approved these changes
Thank you for adding the changes @shaggyyy2002

2022-02-19 22:14 UTC, AvidCoder101 approved these changes

2022-02-19 22:15 UTC, merged

2022-02-19 22:15 UTC, CodingSpecies commented
@all-contributors please add @shaggyyy2002  for content