assignmentdone by hira
jobream/List-of-Learning-Resources pull request #121
Opened 2022-06-10 18:32 UTC by hira-sajid

I have completed

2022-06-10 18:59 UTC, CodingSpecies requested changes
@hira-sajid please can you explain the changes you have made please. Right now, all I see is that the free code camp link has been copied and pasted here: 
![image](https://user-images.githubusercontent.com/70807500/173132463-47e06063-3199-4607-937f-15902731231c.png)

If you need any help feel free to ask below. Thank you.

2022-07-28 15:17 UTC, AvidCoder101 commented
@hira-sajid do you need any help :)

2022-10-23 16:28 UTC, cadamini commented on resources/LearnPython.md
> +                                                                                                                                                                                        |
```suggestion
| [freeCodeCamp](https://www.freecodecamp.org/learn/scientific-computing-with-python/) | freeCodeCamp covers Python fundamentals like variables, loops, conditionals, and functions. Then you'll quickly ramp up to complex data structures, networking, relational databases, and data visualization.  |
```

There have been extra tabs.

2022-10-23 16:30 UTC, cadamini commented on resources/LearnPython.md
> +                                                                                                                                                                                        |
It's also on line 18 (master?)

2023-01-21 05:01 UTC, closed without merging